"""add board_member_visibility

Revision ID: 6995226e64d4
Revises: 02f8f0a1ea34
Create Date: 2026-06-21 14:03:27.182200

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '6995226e64d4'
down_revision: str | None = '02f8f0a1ea34'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_member_visibility',
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('board_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('board_member_visibility')
    # ### end Alembic commands ###
